version: 0.2

env:
  variables:
    GO_VERSION: 1.21.4
phases:
  install:
    commands:
      # install latest version of go
      - wget https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz
      - tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz
      - export PATH="/usr/local/go/bin:$PATH" && export GOPATH="$HOME/go" && export PATH="$GOPATH/bin:$PATH"
  pre_build:
    commands:
      - echo Starting build...
  build:
    commands:
      - echo Building...
      - echo $CODEBUILD_SRC_DIR
      - cd $CODEBUILD_SRC_DIR && go build
  post_build:
    commands:
      - echo Build finished...
        #- aws s3 cp $CODEBUILD_SRC_DIR/nicked.io s3://code.deploy.lightsail.bucket/
